brightness : 64
contrast : 128
saturation : 128
sharpness : 128
gain : 255
focus_auto : false
focus_absolute : -1
exposure_auto : 1
exposure_absolute : 80
white_balance_temperature_auto : false
white_balance_temperature : 4000